# Generated by Django 3.2.14 on 2022-08-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
            ],
        ),
    ]
