# Generated by Django 3.2.14 on 2022-08-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasave',
            name='conform_password',
        ),
        migrations.RemoveField(
            model_name='datasave',
            name='email',
        ),
        migrations.RemoveField(
            model_name='datasave',
            name='password',
        ),
        migrations.RemoveField(
            model_name='datasave',
            name='username',
        ),
    ]
